@echo off
setlocal enabledelayedexpansion

if "%~2"=="" (
    echo WhatsApp Bulk Sender v1.0
    echo Usage: whatsapp-sender ^<numbers_file^> "^<message^>"
    echo.
    echo Example:
    echo   whatsapp-sender numbers.txt "Hello! This is a test"
    exit /b 1
)

set NUMBERS_FILE=%~1
set MESSAGE=%~2

if not exist "%NUMBERS_FILE%" (
    echo Error: Numbers file not found
    exit /b 1
)

echo ========================================
echo    WhatsApp Bulk Sender v1.0
echo ========================================
echo.
echo Numbers file: %NUMBERS_FILE%
echo Message: %MESSAGE%
echo.

set OUTPUT=whatsapp_links.html

echo Creating WhatsApp links...

(
echo ^<!DOCTYPE html^>
echo ^<html^>
echo ^<head^>
echo ^<meta charset="UTF-8"^>
echo ^<title^>WhatsApp Bulk Sender^</title^>
echo ^<style^>
echo body{font-family:Arial;background:linear-gradient(135deg,#25D366,#128C7E^);padding:20px;min-height:100vh;}
echo .container{max-width:900px;margin:0 auto;background:white;border-radius:15px;padding:40px;box-shadow:0 20px 60px rgba(0,0,0,0.3^);}
echo h1{color:#25D366;text-align:center;font-size:2.5em;margin-bottom:10px;}
echo .subtitle{text-align:center;color:#666;margin-bottom:30px;}
echo .stats{background:#f0f9ff;padding:20px;border-radius:10px;margin-bottom:30px;border-left:4px solid #25D366;}
echo .message-preview{background:#fff9e6;padding:20px;border-radius:10px;margin-bottom:30px;border-left:4px solid #ffc107;}
echo .message-preview h3{color:#f57c00;margin-bottom:10px;}
echo .link-card{background:#f8f9fa;padding:15px 20px;margin:10px 0;border-radius:8px;display:flex;align-items:center;justify-content:space-between;transition:all 0.3s;}
echo .link-card:hover{background:#e8f5e9;transform:translateX(5px^);}
echo .number{font-size:1.1em;font-weight:bold;color:#333;}
echo .whatsapp-btn{background:#25D366;color:white;padding:12px 30px;border-radius:25px;text-decoration:none;font-weight:bold;transition:all 0.3s;}
echo .whatsapp-btn:hover{background:#128C7E;transform:scale(1.05^);}
echo .counter{position:fixed;top:20px;right:20px;background:white;padding:15px 25px;border-radius:10px;box-shadow:0 5px 15px rgba(0,0,0,0.2^);}
echo .counter-number{font-size:2em;font-weight:bold;color:#25D366;}
echo .counter-label{color:#666;font-size:0.9em;}
echo .instructions{background:#e3f2fd;padding:20px;border-radius:10px;margin-top:30px;border-left:4px solid #2196f3;}
echo .instructions h3{color:#1976d2;margin-bottom:15px;}
echo .instructions ol{margin-left:20px;color:#555;line-height:1.8;}
echo ^</style^>
echo ^</head^>
echo ^<body^>
echo ^<div class="counter"^>
echo ^<div class="counter-number" id="sent-count"^>0^</div^>
echo ^<div class="counter-label"^>Messages Sent^</div^>
echo ^</div^>
echo ^<div class="container"^>
echo ^<h1^>📱 WhatsApp Bulk Sender^</h1^>
echo ^<p class="subtitle"^>Click each link to send your message^</p^>
echo ^<div class="message-preview"^>
echo ^<h3^>💬 Your Message:^</h3^>
echo ^<div^>%MESSAGE%^</div^>
echo ^</div^>
echo ^<div class="instructions"^>
echo ^<h3^>📋 How to Use:^</h3^>
echo ^<ol^>
echo ^<li^>Click the green "Send on WhatsApp" button^</li^>
echo ^<li^>WhatsApp Web will open with the message ready^</li^>
echo ^<li^>Click Send in WhatsApp^</li^>
echo ^<li^>Close tab and return for next number^</li^>
echo ^<li^>Press 'n' key for quick next^</li^>
echo ^</ol^>
echo ^</div^>
echo ^<div class="links-container"^>
echo ^<h2 style="color:#333;margin:20px 0;"^>📞 Recipients:^</h2^>
) > "%OUTPUT%"

set COUNT=0
for /f "usebackq delims=" %%n in ("%NUMBERS_FILE%") do (
    set /a COUNT+=1
    set NUMBER=%%n
    call :encode_message
    echo ^<div class="link-card"^>^<span class="number"^>!COUNT!. +!NUMBER!^</span^>^<a href="https://wa.me/!NUMBER!?text=!ENCODED_MSG!" class="whatsapp-btn" target="_blank" onclick="incrementCounter(^)"^>📤 Send on WhatsApp^</a^>^</div^> >> "%OUTPUT%"
)

(
echo ^</div^>
echo ^<p style="text-align:center;margin-top:40px;color:#999;"^>Generated by WhatsApp Bulk Sender v1.0^</p^>
echo ^</div^>
echo ^<script^>
echo let sentCount=0;
echo function incrementCounter(^){sentCount++;document.getElementById('sent-count'^).textContent=sentCount;}
echo document.addEventListener('keydown',function(e^){if(e.key==='n'^^||e.key==='N'^){const links=document.querySelectorAll('.whatsapp-btn'^);if(sentCount^<links.length^){links[sentCount].click(^);}}});
echo ^</script^>
echo ^</body^>
echo ^</html^>
) >> "%OUTPUT%"

echo.
echo ✓ Links generated successfully!
echo 📄 Output: %OUTPUT%
echo.
echo Found %COUNT% numbers
echo Opening in browser...

start "" "%OUTPUT%"
exit /b 0

:encode_message
set ENCODED_MSG=%MESSAGE: =%%20%
set ENCODED_MSG=%ENCODED_MSG:!=%%21%
goto :eof